### ISSUE TITLE
Support of initializer lists?

### ISSUE THREAD

**Issue by prokls** [sbeyer/commonsat#1]
Hi,

I have been working on abstract SAT solver interfaces myself to make SAT solver exchanging easily possible. I liked the idea of initializer lists because they do not ask the user to initialize an array on the stack. This makes the code more readable.

The question is: Is the support of initializer lists also planned for this project? Because I think that's the way to go.

You can check out my implementation here: [Abstract SAT solver interface](http://lukas-prokop.at/proj/snippets/cpp003.html)

best regards,
prokls

**Comment by sbeyer** [comment]
Hi,

sorry for the late reply. I noticed that I do not get mails from GitHub, and hence I overlook things easily.

CommonSAT is not my highest-priority project as you might have noticed and many features are missing, but I think it has some kind of initializer lists since the very beginning by just using std::vector functionality. See, e.g., https://github.com/sbeyer/commonsat/blob/master/test/tests.h

**Comment by prokls** [comment]
No problem.

You're totally right. How did I miss that? I guess I always thought you need to reference `std::initializer_list` explicitly.

:smiley: So, that's great. Sorry for the noise
